#Um script simples para iniciar minha conta no github
#by Ch4mpz
import time
print('█───█─▄▀▀─█───▄▀▀─▄▀▀▄─█▄─▄█─▄▀▀')
time.sleep(1)
print('█───█─█───█───█───█──█─█▀▄▀█─█──')
time.sleep(1)
print('█───█─█▀▀─█───█───█──█─█─▀─█─█▀▀')
time.sleep(1)
print('█▄█▄█─█───█───█───█──█─█───█─█──')
time.sleep(1)
print('─▀─▀───▀▀──▀▀──▀▀──▀▀──▀───▀──▀▀')
time.sleep(1)
n = str(input('Qual o seu nome? '))
import time
time.sleep(1)
print('=' *20)
time.sleep(1)
print('      BEM-VINDO   ')
time.sleep(1)
print('=' *20)
time.sleep(1)
print('\n')
print('Olá', n, 'Seja bem vindo ao primeiro script by Ch4mpz')
time.sleep(1)
print('\n')
print('C-Ya!')
